=== Noxalus/BulletML/BulletML/bulletml.dtd
<!ELEMENT vertical (#PCDATA)>
<!ATTLIST vertical type (absolute|relative|sequence) "absolute">

<!ELEMENT fireRef (param*)>
<!ATTLIST fireRef label CDATA #REQUIRED>

<!ELEMENT changeDirection (direction, term)>

<!ELEMENT bulletml (bullet | fire | action)*>
<!ATTLIST bulletml xmlns CDATA #IMPLIED>
<!ATTLIST bulletml type (none | vertical | horizontal) "none">

<!ELEMENT param (#PCDATA)>

<!ELEMENT actionRef (param*)>
<!ATTLIST actionRef label CDATA #REQUIRED>

<!ELEMENT repeat (times, (action | actionRef)+)>

<!ELEMENT accel
  (
    (((horizontal, vertical?) | (horizontal?, vertical)), term) |
    (((vertical, horizontal?) | (vertical?, horizontal)), term) |
    ((horizontal, term, vertical?) | (horizontal?, term, vertical)) |
    ((vertical, term, horizontal?) | (vertical?, term, horizontal)) |
    (term, ((horizontal, vertical?) | (horizontal?, vertical))) |
    (term, ((vertical, horizontal?) | (vertical?, horizontal)))
  )
>
<!ATTLIST accel label CDATA #IMPLIED>

<!ELEMENT times (#PCDATA)>

<!ELEMENT term (#PCDATA)>

<!ELEMENT wait (#PCDATA)>

<!ELEMENT action (changeDirection | accel | vanish | changeSpeed | repeat | wait | (fire | fireRef) | (action | actionRef))*>
<!ATTLIST action label CDATA #IMPLIED>

<!ELEMENT vanish (#PCDATA)>

<!ELEMENT speed (#PCDATA)>
<!ATTLIST speed type (absolute|relative|sequence) "absolute">

<!ELEMENT color (#PCDATA)>
<!ATTLIST color
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
  alpha CDATA #IMPLIED
>

<!ELEMENT horizontal (#PCDATA)>
<!ATTLIST horizontal type (absolute|relative|sequence) "absolute">

<!ELEMENT bullet (direction?, speed?, color?, (action | actionRef)*)>
<!ATTLIST bullet label CDATA #IMPLIED>

<!ELEMENT direction (#PCDATA)>
<!ATTLIST direction type (aim|absolute|relative|sequence) "aim">

<!ELEMENT changeSpeed (speed, term)>

<!ELEMENT fire
  (
    (direction?, speed?, (bullet | bulletRef)) |
    (speed?, direction?, (bullet | bulletRef)) |
    (direction?, (bullet | bulletRef), speed?) |
    (speed?, (bullet | bulletRef), direction?) |
    ((bullet | bulletRef), direction?, speed?) |
    ((bullet | bulletRef), speed?, direction?)
  )
>
<!ATTLIST fire label CDATA #IMPLIED>

<!ELEMENT bulletRef (param*)>
<!ATTLIST bulletRef label CDATA #REQUIRED>

=== Noxalus/BulletML/Visualizer.Core/Assets/Patterns/sprite.xml
<?xml version="1.0" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <fire>
      <bullet>
        <speed>1</speed>
        <sprite>1</sprite>
        <action>
          <wait>100</wait>
          <fire>
              <direction type="absolute">$rand * 360</direction>
              <speed>1</speed>
              <sprite>3</sprite>
            <bullet />
          </fire>
        </action>
      </bullet>
    </fire>
  </action>
</bulletml>

=== Noxalus/BulletML/Visualizer.Android/Assets/Content/Patterns/sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
    <repeat>
      <times>999</times>
      <action>
        <fire>
          <direction type="sequence">61</direction>
          <speed>1</speed>
          <bullet>
            <action>
              <wait>120</wait>
              <changeDirection>
                <direction type="sequence">-61</direction>
                <term>60</term>
              </changeDirection>
              <changeSpeed>
                <speed>2</speed>
                <term>30</term>
              </changeSpeed>
            </action>
          </bullet>
        </fire>
        <wait>1</wait>
      </action>
    </repeat>
  </action>
</bulletml>

=== Noxalus/BulletML/Tests/Content/FireDirectionSequence2.xml
<?xml version="1.0"?>
<!DOCTYPE bulletml SYSTEM "bulletml.dtd">
<bulletml>
  <action label="top">
      <fire>
        <direction type="absolute">10</direction>
        <speed>1</speed>
        <bullet />
      </fire>
      <fire>
        <direction type="sequence">0</direction>
        <speed>1</speed>
        <bullet />
      </fire>
  </action>
</bulletml>
